version: "3"
services:
  wordpress:
    build: ./
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST_FILE: /run/secrets/database_host
      WORDPRESS_DB_USER_FILE: /run/secrets/database_username
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/database_password
      WORDPRESS_DB_NAME_FILE: /run/secrets/database_name
      WORDPRESS_DEBUG: 1
    volumes:
      #Swap the folder path for plugin vs theme development
      - wordpress:/var/www/html
      #- ../:/var/www/html/wp-content/plugins/plugin-dev
      - ../:/var/www/html/wp-content/themes/theme-dev
    secrets:
      - database_host
      - database_name
      - database_username
      - database_password

volumes:
  wordpress:

secrets:
  database_host:
    file: ./secrets/database_host
  database_name:
    file: ./secrets/database_name
  database_username:
    file: ./secrets/database_username
  database_password:
    file: ./secrets/database_password
